version: '3.8'

services:
  chatbot:
    build:
      context: .
    networks:
      - atom-network
    ports:
      - "7860:7860"
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    tty: true

networks:
  atom-network:
    external: true
    name: docker_default
